permalink: /:year/:month/:day/:title
markdown: kramdown

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: pygments
paginate: 5
paginate_path: "news/page/:num"
excerpt_separator: "\n\n\n"

title : EasyText
description: An Easy text Editor, used to create text, code, data editor.
repo : "https://github.com/easyHelper/EasyText"
author:
  name: QiWang
  email: qiwang0@qq.com

production_url : //easyHelper.github.io/EasyText

JB :
  version : 0.3.0
  BASE_PATH : //easyHelper.github.io/EasyText

  ASSET_PATH : false

  archive_path: /archive/
  atom_path : /atom.xml
  rss_path : /rss.xml